### ISSUE TITLE
tarball for 3.0.2 mismatch with install.py

### ISSUE THREAD

**Issue by vinceskahan** [gjr80/weewx-stackedwindrose#8]
Your 3.0.2 tarball is uninstallable because you have the 'skins' tree down under bin/user but install.py expects it at the top of the directory tree

Note where install.py is looking....
```
(weewx-venv) pi@pi5:/var/tmp/stackedwindrose $ grep skins install.py
                ('skins/StackedWindRose', ['skins/StackedWindRose/skin.conf'])
```

Versus what is really in the tarball structure....
```
(weewx-venv) pi@pi5:/var/tmp $ tar ztvf stackedwindrose-3.0.2.tar.gz
drwxrwxr-x gary/gary         0 2023-07-08 01:07 stackedwindrose/
drwxrwxr-x gary/gary         0 2023-07-08 01:07 stackedwindrose/bin/
drwxrwxr-x gary/gary         0 2023-07-08 01:07 stackedwindrose/bin/user/
drwxrwxr-x gary/gary         0 2023-07-08 01:07 stackedwindrose/bin/user/skins/
drwxrwxr-x gary/gary         0 2023-07-08 01:07 stackedwindrose/bin/user/skins/StackedWindRose/
-rw-rw-r-- gary/gary      6434 2023-07-08 01:07 stackedwindrose/bin/user/skins/StackedWindRose/skin.conf
-rw-rw-r-- gary/gary     48270 2023-07-08 01:07 stackedwindrose/bin/user/stackedwindrose.py
-rw-rw-r-- gary/gary      2180 2023-07-08 01:07 stackedwindrose/changelog
-rw-rw-r-- gary/gary      5741 2023-07-08 01:09 stackedwindrose/install.py
-rw-rw-r-- gary/gary     21581 2023-07-08 01:07 stackedwindrose/readme.txt
```

Workaround is to extract the .tar.gz file to a directory and move skins/ up two levels before running the extension installer.   I suppose an alternate workaround would be to edit install.py to use the unusual paths in the tarball currently.  Whatever makes the tarball and install script match would work.

**Comment by gjr80** [comment]
Thanks. Not sure what happened there, looks like the skins directory was placed incorrectly before I constructed the tarball and then I never did a test install. Have re-packaged correctly and replaced the offending v3.0.2 package.
